import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-[#37453d]'>
      {/* Head and Meta Tags */}
      <Head>
        <title>Signopedia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen flex flex-col' style={{ "height": "100vh", "width": "100vw", "backgroundSize": "cover", "backgroundPosition": 'center 20%', "backgroundRepeat": "no-repeat", "backgroundImage": `url("./bg.webp")` }}>
        {/* Header Component */}
        <Header />
        {/* Body Section */}
        <section className=" flex-grow h-96">
          {/* Hero Section */}
          <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 h-full">
            {/* Text Section */}
            <div className="mr-auto place-self-center lg:col-span-7">
              <h1 className="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl">The smart way to identify any traffic sign in
                seconds.</h1>
              <p className="max-w-2xl mb-6 text-white lg:mb-8 md:text-lg lg:text-xl">Just upload an image and let our AI do the rest. or try some samples</p>
              <a href="/tryitnow" className="inline-flex items-center justify-center px-5 py-3 bg-white text-base font-medium text-center text-gray-900 border border-gray-300 rounded-xl hover:bg-gray-100 focus:ring-4 focus:ring-gray-100">
                Try it Now
                <svg className="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
              </a>
            </div>
            {/* Image Section */}
            <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
            </div>
          </div>
        </section>

      </div>
    </div>
  )
}
